### PR TITLE
Update Python and Julia environments

### PR DESCRIPTION
**Pull request by JamesWrigley**
I just wanted to update Julia but there were a bunch of other changes :eyes: @philsmt, @takluyver, @RobertRosca, I'm guessing some of them are from you?

### CODE REVIEW

**Comment by takluyver** [comment]
Not me :shrug:

**Comment by philsmt** [comment]
Yup, I asked Robert the other day to do the `pasha` one. No clue about the rest 🤷

**Comment by RobertRosca** [comment]
Yeah I bumped pasha and added the line-profiler package on request, forgot to commit the changes. Keeping them here is ok for me, I can make a separate commit for it if you'd prefer.

**Comment by tmichela** [comment]
I added the `pyhdf` package for the last upex at HED. It was present in older environments (at least 202301) but missing in the current one...

**Pull request merged**
